### ISSUE TITLE
Should we move these back into pymbar?

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/pymbar-examples#14]
We've had quite a bit of difficulty keeping things synced between the pymbar-examples and pymbar repositories.  I wonder if we should just keep the pymbar-examples *inside* the pymbar repository, which would allow us to make sure that they actually run with every checkin to the repository

**Comment by jchodera** [comment]
The arguments against this were:
* It is harder for users to find the examples if they are installed somewhere internally (like `/usr/lib/python2.7/site-packages/pymbar/examples/...`)
* We want installation of `pymbar` to be fast and `pymbar` to be lightweight, since it is a dependency for many projects.

The first issue is somewhat solved by suggesting `conda` be the preferred installation route and having the recipe install into something like `~/anaconda/share/pymbar/examples/`, though this still a bit hard to find.

The second issue might be solved by having the datasets be downloaded from [figshare](http://figshare.com) or something.  But I think it's still prohibitive to expect users to grab a 75M package every time they want to install `pymbar`.

@bas-rustenburg at some point suggested using subrepositories as a potential solution?

Another possibility could be two separate `conda` recipes that both use the same github repo as their source tree but package up either just `pymbar` or just `pymbar-examples`?

**Comment by bas-rustenburg** [comment]
I think subtrees might be hard to manage and easily more confusing than having to dig a few directory levels. 

Conda recipe would be easiest IMO.

**Comment by kyleabeauchamp** [comment]
So regarding file size, the *big* datasets are supposed to be dumped in `pymbar-datasets`, not here.  The current master zipfile is only 30MB.

```
ls ~/Downloads/ -lt|head
total 176264
-rw-rw-r-- 1 kyleb kyleb  30482522 Jan  9 13:51 pymbar-examples-master.zip
```

**Comment by mrshirts** [comment]
I'm supportive of putting everything in pymbar, but having separate conda installs for pymbar vs pymbar + examples.  30M (probably more like 70 MB incompressed) is not bad for a git pull.  We can always trim the data as needed.

There's something that feels fundamentally off about putting data sets installed into the main program directory.

**Comment by mrshirts** [comment]
Also, I'd probably prefer naming the large data set one something pymbar-large-examples (or even just pymbar-examples if the other one goes away), rather than pymbar-datasets, since the idea is to let people see how the scripts function in real life, not just provide datasets,

**Comment by kyleabeauchamp** [comment]
So right now, note that we don't have *any* installer for pymbar-examples.  So to me, the key issues is figuring out a way to handle two problems:

1.  Making sure they are up to date as changes are made to pymbar
2.  Figuring out a good way to release / distribute the examples

**Comment by mrshirts** [comment]
>
> So right now, note that we don't have *any* installer for
> pymbar-examples. So to me, the key issues is figuring out a way to handle
> two problems:
>

Well, they don't really need an installer, since you should be able to
download them, and run them immediately (as long as pymbar is installed).

Perhaps I'm old fashioned this way, but my perspective is that code that
doesn't contain functions that other code needs shouldn't have to be
installed anywhere or require any special installation instructions. Pymbar
needs an installer, because other programs depend on it -- pymbar-examples
shouldn't.

>
>    1. Making sure they are up to date as changes are made to pymbar
>    2. Figuring out a good way to release / distribute the examples.
>
> Yes, these are both important.  My feeling with 2 is that github is good
enough.  My feeling with 1 is that examples that can fit should be
maintained together, for ease of keeping compatibility of examples and
being able to run regression tests on them.

**Comment by jchodera** [comment]
The `pymbar-examples` repo is 75M uncompressed:
```
[LSKI1497:~/code/pymbar/pymbar-examples] choderaj% du -sh .
 75M	.
```
My favored approach right now is to move the examples into the `pymbar` repo so everything can be tested together, then make two different conda recipes, `pymbar` and `pymbar-examples`.  

We'll still need to figure out if we want to put `pymbar` on the PyPI what should be installed, but this is expected to be a minor distribution channel in the future.

**Comment by kyleabeauchamp** [comment]
OK, I think we're mostly in agreement.  I will begin porting this after I hear back from @mrshirts on fixing the issues in the umbrella sampling example.

**Comment by mrshirts** [comment]
Should be ready to merge now with updates in https://github.com/choderalab/pymbar-examples/pull/16.

Note that the harmonic_oscillators in mbar should be used instead of the one here, as it's slightly newer.

**Comment by mrshirts** [comment]
Any guesses on the timing on this move?  I have some MBAR updates that would be useful to have this in the same repository.

**Comment by kyleabeauchamp** [comment]
Maybe we can delay this for now?  I just tested out the download speed for a potential pull request (https://github.com/kyleabeauchamp/pymbar/tree/examples) and it definitely downloads a lot slower--goes from ~3 seconds to ~46 seconds, albeit on my slow home internet connection.

**Comment by jchodera** [comment]
Is that a huge hinderance?  Since we'll break these up into separate `conda` packages (`pymbar` and `pymbar-examples`), it won't have a huge impact for users that just want to install `pymbar`.

Or is there something I'm not considering here?

**Comment by kyleabeauchamp** [comment]
Im ok with it, but it's big enough they we should discuss first

**Comment by mrshirts** [comment]
I think this shouldn't be an obstacle to people who need to use it using it.

**Comment by kyleabeauchamp** [comment]
OK, I will move these once #18 is merged

**Comment by kyleabeauchamp** [comment]
Done.  See https://github.com/choderalab/pymbar/pull/157/ and https://github.com/choderalab/pymbar-examples/pull/19
